services:
  psql:
    container_name: psql
    image: postgres:17.6-alpine3.22
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 5s

  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    environment:
      DB_HOST: psql     # <-- deve bater com o nome do serviço do Postgres
      DB_PORT: 5432
    depends_on:
     psql:
      container_name: psql
      image: postgres:17.6-alpine3.22
      volumes:
        - ./data/postgres/data:/var/lib/postgresql/data/
      env_file:
        - ./dotenv_files/.env
      healthcheck:
        # use $$ para que as variáveis sejam expandidas dentro do container
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
        interval: 5s
        timeout: 3s
        retries: 12
        start_period: 5s
